server:
  port: 63001

# Dubbo极简配置
dubbo:
  application:
    name: dubbo-client
  registry:
    address: zookeeper://127.0.0.1:2181
    # 大伙请换成自己的zookeeperip
    protocol: zookeeper
    # 启动时检查是否存在，注册中心不存在就报错
    check: false
  # 元数据中心
  metadata-report:
    address: zookeeper://127.0.0.1:2181
  # 协议配置，
  protocol:
    # name必填，指定协议类型 => dubbo协议缺省端口为20880，rmi为1099，http和hessian为80
    name: dubbo
  monitor:
    # 监控中心, 用于配置连接监控中心相关信息，可选
    protocol: register